
<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

use Magento\Framework\App\Action\Action;

/** @var \Magento\CatalogWidget\Block\Product\ProductsList $block */
$dateModel =$currenttime="";
// phpcs:disable Generic.Files.LineLength.TooLong
// phpcs:disable Magento2.Templates.ThisInTemplate.FoundHelper
$brand = $block->getBrands();
$currenttime = $block->getCurrentGMTDateTime();
$objectManager = \Magento\Framework\App\ObjectManager::getInstance(); // Instance of Object Manager
$priceHelper = $objectManager->create('Magento\Framework\Pricing\Helper\Data'); // Instance of Pricing Helper

// print_r($parameter);
?>
<?php if ($exist = ($block->getProductCollection() && $block->getProductCollection()->getSize())): ?>
    
   <?php
    $type = 'widget-product-grid';
    $dateModel ="";
    $mode = 'grid';

    $image = 'new_products_content_widget_grid';
    $items = $block->getProductCollection()->getItems();

    $showWishlist = true;
    $showCompare = true;
    $showCart = true;
    $templateType = \Magento\Catalog\Block\Product\ReviewRendererInterface::SHORT_VIEW;
    $description = false;
   
    ?>
    <style>
        .block.widget .product-item-info {
    position: relative;
}

.block.widget .product-item-info .dealoffer {
    top: 50px;
    left: 0px;
    position: absolute;
    z-index: 999;
    width: auto;
    padding: revert;
    color: #fcfcfc;
    background-color: #3baa3b;
}
    </style>
    <div class="block widget block-products-list <?= /* @noEscape */ $mode ?>">
        <?php if ($block->getproduct()->getTitle()): ?>
            <div class="block-title">
                <strong><?= $block->getproduct()->escapeHtml(__($block->getproduct()->getTitle())) ?></strong>
            </div>
        <?php endif ?>
        <div class="block-content">
            <?= /* @noEscape */ '<!-- ' . $image . '-->' ?>
            <div class="products-<?= /* @noEscape */ $mode ?> <?= /* @noEscape */ $mode ?>">
                <ol class="product-items <?= /* @noEscape */ $type ?>">
                    <?php $iterator = 1; ?>
                    <?php foreach ($items as $_item): 
                        ?>
                        <?= /* @noEscape */ ($iterator++ == 1) ? '<li class="product-item">' : '</li><li class="product-item">' ?>
                        <div class="product-item-info">
                            <a href="<?= $block->getproduct()->escapeUrl($block->getproduct()->getProductUrl($_item)) ?>" class="product-item-photo">
                                <?= $block->getproduct()->getImage($_item, $image)->toHtml() ?>
                            </a>
                            <?php if($_item->getDiscountType()=="percentage"){ ?>
                             <button class="dealoffer"><?php echo 100-$_item->getDealValue(); ?>% off</button>
                          <?php }else {
                            $price =  (int)$_item->getPrice();
                          $prices = 100*$_item->getDealValue()/$price;
                          
                          ?>
                         
                              <button class="dealoffer" ><?php echo 100-round($prices);?>% off</button>
                         <?php } ?>
                            <div class="product-item-details">
                                <strong class="product-item-name">
                                    <a title="<?= $block->getproduct()->escapeHtml($_item->getName()) ?>"
                                       href="<?= $block->getproduct()->escapeUrl($block->getproduct()->getProductUrl($_item)) ?>"
                                       class="product-item-link">
                                        <?= $block->getproduct()->escapeHtml($_item->getName()) ?>
                                    </a>
                                </strong>
                               
                                <?php if ($templateType): ?>
                                    <?= $block->getproduct()->getReviewsSummaryHtml($_item, $templateType) ?>
                                <?php endif; ?>

                                <?= $block->getproduct()->getProductPriceHtml($_item, $type) ?>
                                <div style="color: #666666;font-weight: 600;letter-spacing: .05em;text-transform: uppercase;"><?php echo "Deals Ends In"; ?>
                                </div>
                                <div>
                                    <script type="text/javascript">// <![CDATA[
                                        function getTimer()
                                        {
                                            
                                            dt = new Date("<?php echo $_item->getDealTo(); ?>");
                                            dt = dt.getTime();
                                            
                                            no = new Date("<?php echo __($block->getCurrentGMTDateTime()) ?>");
                                            setInterval(function(){no}, 1000);
                                            no = no.getTime();
                                            var end = dt;
                                            var now_date = no;
                                            var _second = 1000;
                                            var _minute = _second * 60;
                                            var _hour = _minute * 60;
                                            var _day = _hour * 24;
                                            flag_time = true;
                                            timer = '';
                                    
                                            setInterval(function(){showRemaining();}, 1000);
                                    
                                            function showRemaining()
                                            {
                                                var date = no;
                                                var now = new Date(date);
                                                var de = now.getTime();
                                    
                                                if (flag_time) {
                                                    timer = de;
                                                }
                                                var d = new Date(timer);
                                                currentYear = d.getFullYear();
                                                month = d.getMonth() + 1;
                                    
                                                var currentDate = d.getDate();
                                                currentDate = currentDate < 10 ? '0'+currentDate : currentDate;
                                    
                                                var hours = d.getHours();
                                                var minutes = d.getMinutes();
                                                var seconds = d.getSeconds();
                                    
                                                minutes = minutes < 10 ? '0'+minutes : minutes;
                                                seconds = seconds < 10 ? '0'+seconds : seconds;
                                                var strTime = hours + ':' + minutes+ ':' + seconds;
                                                timer = timer + 1000;
                                                var now_time = currentYear + '/' + month + '/' + currentDate + ' ' + strTime;
                                    
                                                var now = new Date(now_time);
                                                var distance = end - now;
                                    
                                                if (distance < 0) {
                                                    if (distance > -3)
                                                    {
                                                        location.reload(true);
                                                        return;
                                                    };
                                    
                                                    clearInterval(timer);
                                                    document.getElementById('<?php echo $_item->getSku();?>').innerHTML = 'Completed';
                                                    return;
                                                }
                                                var days = Math.floor(distance / _day);
                                                var hours = Math.floor((distance % _day) / _hour);
                                                var minutes = Math.floor((distance % _hour) / _minute);
                                                var seconds = Math.floor((distance % _minute) / _second);
                                                if (days < 10)
                                                    {days = '0' + days;}
                                                if (hours < 10)
                                                    {hours = '0' + hours;}
                                                if (minutes < 10)
                                                   { minutes = '0' + minutes;}
                                                if (seconds < 10)
                                                    {seconds = '0' + seconds;}
                                    
                                                if (days==00)
                                                {
                                                    dytext = '';
                                                }
                                                else if(days==1)
                                                {
                                                    dytext = '<span class="countdown-text">'+ days +' Day  </span>';
                                                }
                                                else
                                                {
                                                     dytext = '<span class="countdown-text">'+ days +' Days  </span>';
                                                }
                                    
                                                if(hours==00) {
                                                    hrtext='';
                                                }
                                                else {
                                                    hrtext = '<span class="countdown-text">'+ hours + '</span>'+ ":";
                                                }
                                    
                                                if(minutes==00)
                                                {
                                                    mintext='';
                                                }
                                                else {
                                                    mintext = '<span class="countdown-text">'+ minutes +'</span>'+ ":";
                                                }
                                    
                                                sectext = '<span class="countdown-text">'+ seconds +'</span>';
                                                document.getElementById('<?php echo $_item->getSku();?>').innerHTML = dytext + hrtext +  mintext + sectext;
                                                flag_time = false;
                                            }
                                        }
                                        // ]]></script>
                                    
                                        <span id="<?php echo $_item->getSku();?>">
                                            <script type="text/javascript">// <![CDATA[
                                            getTimer()
                                    
                                            // ]]></script>
                                        </span>
                                
                                </div>
                                
                               
                                <?php if($_item->getDiscountType()=="percentage"){ ?>
                                  
                                    <p>Save on Deal 
                                         <?php $price =  (int)$_item->getPrice();
                                         $prices = $price/100*$_item->getDealValue();
                                         $prices = $price - $prices;
                                        
                                        
                                         echo $block->getPriceformate(round($prices));
                                          ?>
                                       
                                    
                                    </p>
                                  
                                    <?php }else{
                                        $price =  (int)$_item->getPrice();
                                        $prices=$price-$_item->getDealValue();
                                        ?>
                                        
                                        <p>
                                            Save on Deal <?php
                                            echo $block->getPriceformate(round($prices));
                                            ?>
                                        </p>
                                
                                        <?php
                                        
                                    } ?>
                                <?= $block->getproduct()->getProductDetailsHtml($_item) ?>

                            
                                <?php if ($showWishlist || $showCompare || $showCart): ?>
                                    <div class="product-item-inner">
                                        <div class="product-item-actions">
                                            <?php if ($showCart): ?>
                                                <div class="actions-primary">
                                                    <?php if ($_item->isSaleable()): ?>
                                                        <?php $postParams = $block->getproduct()->getAddToCartPostParams($_item); ?>
                                                        <form data-role="tocart-form" data-product-sku="<?= $block->getproduct()->escapeHtml($_item->getSku()) ?>" action="<?= $block->getproduct()->escapeUrl($postParams['action']) ?>" method="post">
                                                            <input type="hidden" name="product" value="<?= $block->getproduct()->escapeHtmlAttr($postParams['data']['product']) ?>">
                                                            <input type="hidden" name="<?= /* @noEscape */ Action::PARAM_NAME_URL_ENCODED ?>" value="<?= /* @noEscape */ $postParams['data'][Action::PARAM_NAME_URL_ENCODED] ?>">
                                                            <?= $block->getproduct()->getBlockHtml('formkey') ?>
                                                            <button type="submit"
                                                                    title="<?= $block->getproduct()->escapeHtml(__('Add to Cart')) ?>"
                                                                    class="action tocart primary">
                                                                <span><?= $block->getproduct()->escapeHtml(__('Add to Cart')) ?></span>
                                                            </button>
                                                        </form>
                                                    <?php else: ?>
                                                        <?php if ($_item->isAvailable()): ?>
                                                            <div class="stock available"><span><?= $block->getproduct()->escapeHtml(__('In stock')) ?></span></div>
                                                        <?php else: ?>
                                                            <div class="stock unavailable"><span><?= $block->getproduct()->escapeHtml(__('Out of stock')) ?></span></div>
                                                        <?php endif; ?>
                                                    <?php endif; ?>
                                                </div>
                                            <?php endif; ?>
                                            <?php if ($showWishlist || $showCompare): ?>
                                                <div class="actions-secondary" data-role="add-to-links">
                                                    <?php if ($this->helper(\Magento\Wishlist\Helper\Data::class)->isAllow() && $showWishlist): ?>
                                                        <a href="#"
                                                           data-post='<?= /* @noEscape */ $block->getproduct()->getAddToWishlistParams($_item) ?>' class="action towishlist" data-action="add-to-wishlist" title="<?= $block->getproduct()->escapeHtmlAttr(__('Add to Wish List')) ?>">
                                                            <span><?= $block->getproduct()->escapeHtml(__('Add to Wish List')) ?></span>
                                                        </a>
                                                    <?php endif; ?>
                                                    <?php if ($block->getproduct()->getAddToCompareUrl() && $showCompare): ?>
                                                        <?php $compareHelper = $this->helper(\Magento\Catalog\Helper\Product\Compare::class);?>
                                                        <a href="#" class="action tocompare" data-post='<?= /* @noEscape */ $compareHelper->getPostDataParams($_item) ?>' title="<?= $block->getproduct()->escapeHtmlAttr(__('Add to Compare')) ?>">
                                                            <span><?= $block->getproduct()->escapeHtml(__('Add to Compare')) ?></span>
                                                        </a>
                                                    <?php endif; ?>
                                                </div>
                                            <?php endif; ?>
                                        </div>
                                    </div>
                                <?php endif; ?>
                            </div>
                        </div>
                        <?= ($iterator == count($items) + 1) ? '</li>' : '' ?>
                    <?php  endforeach ?>
                </ol>
            </div>
            
            <?= $block->getPagerHtml() ?>
        </div>
    </div>
    <div>
        
    </div>
    
    <?php if($block->getBlockHtml('formkey')): ?>
    <script type="text/x-magento-init">
    {
        ".block.widget [data-role=tocart-form]": {
            "Magento_Catalog/js/validate-product": {}
        }
    }
    </script>
    <?php endif;?>

<?php
else: ?>
<div style="padding:unset;">No product Found</div>
<?php
endif;

