<?php
$objectManager = \Magento\Framework\App\ObjectManager::getInstance(); // Instance of Object Manager
$priceHelper = $objectManager->create('Magento\Framework\Pricing\Helper\Data'); // Instance of Pricing Helper


$product =$block->getCurrentProduct();
$currenttime = $block->getCurrentGMTDateTime();
$sumbol = $block->getCurrentCurrencySymbol();
$dealvalue = $product->getDealValue();
$dealenable = $product->getDailyDeal();
$dealfrom = $product->getDealFrom();
$dealto = $product->getDealTo();
$dealtype = $product->getDiscountType();
$price = $product->getPrice();
if($dealenable == 1 && $dealfrom <= $currenttime && $currenttime <= $dealto && $dealvalue){
?>
<style>
    .saveondeal button {
    border: none;
    background: #228B22;
    color: #fff;
}
.saveondeal span {
    font-weight: 600;
}
.deal-priceblock-timer .deal-timer #countdown {
    display: inline-flex;
    justify-content: space-between;
    margin-bottom: 15px;
    text-align: center;
    gap: 15px;
}
.deal-priceblock-timer .deal-timer .countdown-text b {
    display: block;
    text-align: center;
    font-size: 2rem;
}

.deal-priceblock-timer .deal-timer .countdown-text {
    text-align: center;
    display: block;
}
.deal-priceblock-timer ~  .price-box.price-final_price {
    width: 50%;
    float: left;
}
.deal-priceblock-timer {
    float: right;
    width: 50%;
}

.deal-priceblock-timer ~ .price-box.price-final_price .price-container {
    display: inline-block !important;
    width: 100%;
}

.product-info-main .product-info-price .deal-priceblock-timer ~ .price-box.price-final_price .price-label {
    display: block;
    float: none;line-height: initial;
    margin: 0;
}
.product-info-main .product-info-price .deal-priceblock-timer ~ .price-box.price-final_price  .price {
    padding-left: 0;
}
.product-info-main .product-info-price .deal-priceblock-timer ~ .price-box.price-final_price .price-wrapper {
    line-height: initial;
    margin: 0;
}
.product-info-stock-sku {
    width: 100%;
    padding: 0 !important;
}
</style>
 <div class="deal-priceblock-timer">
<div class="deal-end-in">Deals Ends In</div>
<div class="deal-timer">
    <script type="text/javascript">// <![CDATA[
        function getTimer()
        {
            dt = new Date("<?php echo $product->getDealTo(); ?>");
            dt = dt.getTime();
            no = new Date("<?php echo $currenttime ;?>");
            no = no.getTime();
            var end = dt;
            var now_date = no;
            var _second = 1000;
            var _minute = _second * 60;
            var _hour = _minute * 60;
            var _day = _hour * 24;
            flag_time = true;
            timer = '';
    
            setInterval(function(){showRemaining();}, 1000);
    
            function showRemaining()
            {
                var date = no;
                var now = new Date(date);
                var de = now.getTime();
    
                if (flag_time) {
                    timer = de;
                }
                var d = new Date(timer);
                currentYear = d.getFullYear();
                month = d.getMonth() + 1;
    
                var currentDate = d.getDate();
                currentDate = currentDate < 10 ? '0'+currentDate : currentDate;
    
                var hours = d.getHours();
                var minutes = d.getMinutes();
                var seconds = d.getSeconds();
    
                minutes = minutes < 10 ? '0'+minutes : minutes;
                seconds = seconds < 10 ? '0'+seconds : seconds;
                var strTime = hours + ':' + minutes+ ':' + seconds;
                timer = timer + 1000;
                var now_time = currentYear + '/' + month + '/' + currentDate + ' ' + strTime;
    
                var now = new Date(now_time);
                var distance = end - now;
    
                if (distance < 0) {
                    if (distance > -3)
                    {
                        location.reload(true);
                        return;
                    };
    
                    clearInterval(timer);
                    document.getElementById('countdown').innerHTML = 'Completed';
                    return;
                }
                var days = Math.floor(distance / _day);
                var hours = Math.floor((distance % _day) / _hour);
                var minutes = Math.floor((distance % _hour) / _minute);
                var seconds = Math.floor((distance % _minute) / _second);
                if (days < 10)
                    {days = '0' + days;}
                if (hours < 10)
                    {hours = '0' + hours;}
                if (minutes < 10)
                   { minutes = '0' + minutes;}
                if (seconds < 10)
                    {seconds = '0' + seconds;}
    
                if (days==00)
                {
                    dytext = '';
                }
                else if(days==1)
                {
                    dytext = '<span class="countdown-text">'+'<b>'+ days+'</b>'+' Day  </span>';
                }
                else
                {
                     dytext = '<span class="countdown-text">'+ '<b>'+ days+'</b>' +' Days  </span>';
                }
    
                if(hours==00) {
                    hrtext='';
                }else if(hours==01){
                    hrtext = '<span class="countdown-text">'+'<b>'+ hours +'</b>'+' Hour  </span>' ;
                }
                else {
                    hrtext = '<span class="countdown-text">'+'<b>'+ hours +'</b>'+' Hours  </span>';
                }
    
                if(minutes==00)
                {
                    mintext='';
                }else if(minutes==01){
                    mintext = '<span class="countdown-text">'+'<b>'+ minutes +'</b>'+' Minute  </span>';
                }
                else {
                    mintext = '<span class="countdown-text">'+'<b>'+ minutes +'</b>'+' Minutes  </span>';
                }
    
                sectext = '<span class="countdown-text">'+'<b>'+ seconds +'</b>'+' Seconds  </span>';
                document.getElementById('countdown').innerHTML = dytext + hrtext +  mintext + sectext;
                flag_time = false;
            }
        }
        // ]]></script>
    
        <span id="countdown">
            <script type="text/javascript">// <![CDATA[
            getTimer()
    
            // ]]></script>
        </span>

</div>
		 <?php if($product->getDiscountType()=="percentage"){ ?> 
   <div class="saveondeal"> 
   <button> <?php echo 100-$product->getDealValue(); ?> % off</button>
    <span> Save on Deal 
         <?php $price =  (int)$product->getPrice();
         $prices = $price/100*$product->getDealValue();
         $prices = $price - $prices;
         $prices = $priceHelper->currency(round($prices), true, false);
         
         echo $prices;
          ?>
       
    
    </span>
   </div>
    <?php }else{
        $price =  (int)$product->getPrice();
        $percenet = $product->getDealValue()/$price*100;
        $prices = $price - $product->getDealValue();
        $prices = $priceHelper->currency($prices, true, false);
        
        ?>
        <div class="saveondeal">
            <button><?php echo 100-round($percenet); ?> % off</button> 
			<span>Save on Deal <?php
            echo $prices;
            ?>
			</span>
        </div>
        <?php
        
    } 
    ?>
</div>
    <?php
}?>

