<?php
$objectModelManager = \Magento\Framework\App\ObjectManager::getInstance ();
$id = $block->getProduct()->getSellerId();
$customerObj = $objectModelManager->create('Magento\Customer\Model\Customer')->load($id);
$sellerName = $customerObj->getName ();
$sellerEmail = $customerObj->getEmail ();

?>
<form data-mage-init='{"validation": {}}' class="review-form" action="<?php echo $block->getPathUrl() ?>"
    id="my-form" method="post" autocomplete="on">
    <fieldset class="fieldset">
      <div class="field name required">
        
        <input type="hidden" class="form-control" data-validate='{"required":true}' maxlength="20" id="field-1"
          value='<?php echo $block->getCustomer()->getName();?>' placeholder="<?php echo __('Enter name')?>" name="c_name">

      </div>
      <div class="field name required">
        
        <input type="hidden" class="form-control"
          id="field-2" value="<?php echo $block->getCustomer()->getId();?>" name="c_id">
      </div>
      <div class="field name required">
        
        <input type="hidden" data-validate="{required:true, 'validate-email':true}" class="form-control"
          id="field-2" value="<?php echo $block->getCustomer()->getEmail();?>"
          placeholder="<?php echo __('Enter email')?>" name="c_email">
      </div>
      <input type="hidden" value="<?php echo $sellerEmail; ?>" readonly class="form-control"
        name="s_email">

      <input type="hidden" data-validate='{"required":true}'
        value="<?php echo $block->getProduct()->getSellerId(); ?>" readonly class="form-control" id="field-52"
        name="s_id">
        <input type="hidden" data-validate='{"required":true}'
        value="<?php echo $sellerName; ?>" readonly class="form-control" id="field-52"
        name="s_name">

        <input type="hidden" data-validate='{"required":true}' value="<?php echo $block->getProduct()->getId(); ?>"
readonly class="form-control" id="field-53" name="product_id">
      
    </fieldset>
       
    <button style="background-color:#006bb4;color:white;" type="submit" class="btn btn-default">
      <?php echo __('Add to favourite')?>
    </button>
  </form>
 