
<?php
$objectModelManager = \Magento\Framework\App\ObjectManager::getInstance ();
$customerObj = $objectModelManager->create('Magento\Customer\Model\Session');
$sellerId = $customerObj->getId();
$act="";
$selleremail="";
$sellerName='';
if($sellerId){


?>
<style>
table { 
	width: 750px; 
	border-collapse: collapse; 
	margin:50px auto;
	}

/* Zebra striping */
tr:nth-of-type(odd) { 
	background: #eee; 
	}

th { 
	background: #3498db; 
	color: white; 
	font-weight: bold; 
	}

td, th { 
	padding: 10px; 
	border: 1px solid #ccc; 
	text-align: left; 
	font-size: 18px;
	}

/* 
Max width before this PARTICULAR table gets nasty
This query will take effect for any screen smaller than 760px
and also iPads specifically.
*/
@media 
only screen and (max-width: 760px),
(min-device-width: 768px) and (max-device-width: 1024px)  {

	table { 
	  	width: 100%; 
	}

	/* Force table to not be like tables anymore */
	table, thead, tbody, th, td, tr { 
		display: block; 
	}
	
	/* Hide table headers (but not display: none;, for accessibility) */
	thead tr { 
		position: absolute;
		top: -9999px;
		left: -9999px;
	}
	
	tr { border: 1px solid #ccc; }
	
	td { 
		/* Behave  like a "row" */
		border: none;
		border-bottom: 1px solid #eee; 
		position: relative;
		padding-left: 50%; 
	}

	td:before { 
		/* Now like a table header */
		position: absolute;
		/* Top/left values mimic padding */
		top: 6px;
		left: 6px;
		width: 45%; 
		padding-right: 10px; 
		white-space: nowrap;
		/* Label the data */
		content: attr(data-column);

		color: #000;
		font-weight: bold;
	}

}

</style>
<form data-mage-init='{"validation": {}}' class="review-form" action="<?php echo $block->getPathUrl() ?>"
    id="my-form" method="post" autocomplete="on">
    <fieldset class="fieldset">
      <div class="field name required">
      <label class="label" for="field-1"><span>
                  <?php echo __('Subject:');?>
                </span></label>
        <input type="text" class="form-control" data-validate='{"required":true}' maxlength="20" id="field-1"
          value='' name="subject">

      </div>
      <div class="field name required">
      <label class="label" for="field-2"><span>
                  <?php echo __('Message:');?>
                </span></label>
<textarea data-validate='{"required":true}' name="massage" id="comment" class="input-text"></textarea>
</div>
<div class="field name required">
<input style="background-color:#006bb4;color:white;" type="submit" name="submit" value="Send Email" class="btn btn-default" />
     
   
</div>
  <table border="1">

    <tr>
        <th><input type="checkbox" name="acc" id="selectall"/>Select All</th>
        <th>Customer Name</th>
        <th>Follow Date</th>
    
    
    </tr>
    <?php
    $data = $block->getCustomer();
    
    foreach($data as $item){
     if($item['seller_id'] == $sellerId)
     {
        $selleremail = $item['seller_email'];
        $sellerName =$item['seller_name'];
    $act= $sellerId;
    
    ?>
    <tr>
    
    <td width="20" align="center"><input type="checkbox" class="name" name="custome[]" value="<?php echo $item['customer_email']; ?>"/></td>
        
    <td width="92"><?php echo $item['customer_name']; ?></td>
    
    <td width="42"><?php echo $item['added_at']; ?></td>
    
    </tr>
    
    <?php
    }
    
    
    }
    if(!$act){
        ?>
        <tr>
        <td colspan="3">No Any Follower List Here</td>
       </tr>
        <?php
    }
    
    ?>
    
    </table>
    <input type="hidden" class="form-control" data-validate='{"required":true}' maxlength="20" id="field-1"
          value='<?php echo $selleremail ?>' name="s_email">
          <input type="hidden" class="form-control" data-validate='{"required":true}' maxlength="20" id="field-1"
          value='<?php echo $sellerName ?>' name="s_name">
    
</fieldset>

    </form>
    <?php } 
else{ ?>
    <script type="text/javascript">
        function redirectHome() {
          window.location = "{{store url='no-route'}}";
        }
        setTimeout("redirectHome()", 500);
        </script>
   <?php
}?>
  <script type="text/javascript" src="http://ajax.googleapis.com/ajax/libs/jquery/1.3.2/jquery.min.js"></script>

<script language="javascript">

    $(function () {

        // add multiple select / deselect functionality

        $("#selectall").click(function () {

            $('.name').attr('checked', this.checked);

        });

 

        // if all checkbox are selected, then check the select all checkbox

        // and viceversa

        $(".name").click(function () {

 

            if ($(".name").length == $(".name:checked").length) {

                $("#selectall").attr("checked", "checked");

            } else {

                $("#selectall").removeAttr("checked");

            }

 

        });

    });



    $(document).ready(function(){
    $("form").submit(function(){
		if ($('input:checkbox').filter(':checked').length < 1){
        alert("An custome needs to be selected. Select and try again.");
		return false;
		}
    });
});
</script>
