<?php 

$helper = $this->helper('Dotsquares\Productsinquiry\Helper\Data');
$objectManager = \Magento\Framework\App\ObjectManager::getInstance();
$customerSession = $objectManager->get('Magento\Customer\Model\Session');
$product = $objectManager->get('Magento\Catalog\Block\Product\View');
 if($helper->isEnabled()){
   if($helper->getFormType()==false){
     if($product->getProduct()->getEnquiry()){
?>
<div style="padding-bottom: 30px;">
  <button style="background-color:#006bb4;color:white;" type="button" class="btn btn-primary btn-lg" id="popupButton"
    data-toggle="modal" data-target="#myModal">
    <?php echo __($helper->getButtonLavel())?>
  </button>
</div>
<!-- Modal -->

<!-- Modal content -->
<div class="modal fade" id="myModal" style="display:block;">
  <div class="modal-dialog">
    <!-- Modal content -->
    <div class="modal-content">

      <div class="modal-body">
        <form data-mage-init='{"validation": {}}' class="review-form" action="<?php echo $block->getPathUrl() ?>"
          id="my-form" method="post" autocomplete="on">
          <fieldset class="fieldset">
            <div class="field name required">
              <label class="label" for="field-1"><span>
                  <?php echo __('Name');?>
                </span></label>
              <input type="text" class="form-control" data-validate='{"required":true}' maxlength="20" id="field-1"
                value="<?php echo $customerSession->getCustomer()->getName();?>" placeholder="<?php echo __('Enter name')?>" name="c_name">

            </div>
            <div class="field name required">
              <label class="label" for="field-2"><span>
                  <?php echo __('Email');?>
                </span></label>
              <input type="email" data-validate="{required:true, 'validate-email':true}" class="form-control"
                id="field-2" value="<?php echo $customerSession->getCustomer()->getEmail();?>"
                placeholder="<?php echo __('Enter email')?>" name="email">
            </div>
            <div class="field name required">
              <label class="label" for="field-3"><span>
                  <?php echo __('Telephone');?>
                </span></label>

              <input type="number" data-validate='{"required":true}' class="form-control" id="field-3"
                placeholder="<?php echo __('Enter Telephone')?>" pattern="\d{10}" maxlength="10" minlength="10"
                name="telephone">
            </div>

            <input type="hidden" data-validate='{"required":true}'
              value="<?php echo $product->getProduct()->getSku(); ?>" readonly class="form-control" id="field-52"
              name="sku">

              <input type="hidden" data-validate='{"required":true}' value="<?php echo $product->getProduct()->getId(); ?>"
      readonly class="form-control" id="field-53" name="product_id">


            <input type="hidden" data-validate='{"required":true}'
              value="<?php echo $product->getProduct()->getName();?>" readonly class="form-control" id="field-54"
              name="product_name">

            <input type="hidden" data-validate='{"required":true}'
              value="<?php echo $product->getProduct()->getProductUrl();?>" class="form-control" id="field-55"
              placeholder="<?php echo __('Enter Subject')?>" name="producturl">

            <div class="field name required">
              <label class="label" for="field-4"><span>
                  <?php echo __('Subject');?>
                </span></label>

              <input type="text" data-validate='{"required":true}' maxlength="50" class="form-control" id="field-4"
                placeholder="<?php echo __('Enter Subject')?>" name="subject">
            </div>
            <div class="field name required">
              <label class="label" for="field-5"><span>
                  <?php echo __('Message');?>
                </span></label>

              <textarea class="form-control" data-validate='{"required":true}' maxlength="500" rows="5" id="field-5"
                name="massage"></textarea>
            </div>
            <?php if($helper->isreCptchaEnable()): ?>
            <div class="form-group required">
              <div class="g-recaptcha required" id="recaptcha"
                data-sitekey="<?php echo $helper->getreCptchaPrivateKey(); ?>">
              </div>
              <div style="display:none" id="error-msg">
                <span>
                  <?php echo __('This is a required field.') ?>
                </span>
              </div>
            </div>
          </fieldset>
          <?php endif; ?>
          <button style="background-color:#006bb4;color:white;" type="submit" class="btn btn-default">
            <?php echo __('Submit')?>
          </button>
        </form>
      </div>
    </div>
  </div>
</div>



<script>
  require(
      [
          'jquery',
          'Magento_Ui/js/modal/modal'
      ],
      function (
          $,
          modal
      ) {
          var options = {
              type: 'popup',
              responsive: true,
              innerScroll: true,
              clickableOverlay: true,
              title: 'Product Enquiry',
              buttons: [{
                  text: $.mage.__(''),
                  class: '',
                  click: function () {
                      this.closeModal();
                  }
              }]
          };

          var popup = modal(options, $('#myModal'));
          $("#popupButton").on('click', function () {
              $("#myModal").modal("openModal");
          });

      }
  );
</script>
<script type="text/x-magento-init">
    {
        "#my-form": {
            "validation": {}
        }
    }
</script>
<script src="https://www.google.com/recaptcha/api.js" type="text/javascript" xml="space"></script>
<script>
  function checkCaptcha() {
    if ((jQuery('#g-recaptcha-response').val()) === '') {
      jQuery('#error-msg').css('display', 'block');
      jQuery('#error-msg').css('color', '#df280a');
      jQuery('#error-msg').css('font-size', 13);
      return false;
    }
    else {
      jQuery('#error-msg').css('display', 'none');
    }
  }
</script>
<?php
      }
    }
}



?>