<?php 
$width=30;
$height=30;

if($block->getProduct()->getBrands()){
foreach ($block->getBrandCollection() as $item): 
if($item['brand_id']==$block->getProduct()->getBrands()){
?>

<div class="itemm"><a
        href='<?php echo $block-> getPathBaceUrl()."dotsquares/index/brandview"."?"."id=".$item["brand_id"];?>'><img
            style="width:<?php if($block->getPPBLogoWidth()){ echo $block->getPPBLogoWidth();} else{ echo $width; } ?>px; height:<?php if($block->getPPBLogoHeight()){ echo $block->getPPBLogoHeight();} else{ echo $height; } ?>px;"
            src='<?php echo $block-> getPathUrlMedia(). $item["path"] ."/". $item["image"]; ?>' /></a>
    <?php if($block->getPPBSDescription()){ ?>
    <div class="itemmm">
        <p>
            <?php echo $item["sort_detail"]; ?>
        </p>

        <img style="width:70px; height:50px;"
            src='<?php echo $block-> getPathUrlMedia(). $item["path"] ."/". $item["image"]; ?>' />

    </div>
    <?php } ?>
</div>
<?php 
}
endforeach; 

}
?>
<style>
    .itemm {
        position: relative;
    }

    .itemmm {
        background-color: white;
        display: none;
        position: absolute;
        max-width: 300px;
        text-align: center;
        bottom: 30px;
        left: 40px;
        border: 1px solid rgb(70, 67, 67);


    }

    .itemm:hover .itemmm {
        display: block;
    }
</style>