<li class="level0 nav-1 category-item last level-top parent ui-menu-item">
    <a href="<?php echo $block->getUrllink();?>" class="level-top ui-menu-item-wrapper" aria-haspopup="true"
        id="ui-id-2" tabindex="-1" role="menuitem">
        <!-- <span class="ui-menu-icon ui-icon ui-icon-caret-1-e"> -->
        </span><span>
            <?php echo $block->getMenuButtoneName();?>
        </span>
</a>
</li>